print(4 * 5)
print(4 / 5)
print(4 + 5)
print(4 - 5)
print(4 ** 5)
print("24 % 5: ",24 % 5)
print(type(4))
print(type(.8))
print("Hi Mom " * 10)
print("Hi Mom " + " Please do my laundry!")
#print(int("zero"))
print(4 < 6)
print(type(True))
print(type(False))
